# Generated by Django 4.2.18 on 2025-10-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCashflow',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monthly_income_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_variability_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('essential_expenses_avg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'customer_cashflow',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_type', models.CharField(choices=[('loan', 'Loan'), ('card', 'Card')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='financial_restructuring.customercashflow')),
            ],
            options={
                'db_table': 'payments_history',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_rate_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('remaining_term_months', models.IntegerField()),
                ('collateral', models.BooleanField()),
                ('days_past_due', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='financial_restructuring.customercashflow')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credit_score', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_history', to='financial_restructuring.customercashflow')),
            ],
            options={
                'db_table': 'credit_score_history',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_rate_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('min_payment_pct', models.DecimalField(decimal_places=1, max_digits=4)),
                ('payment_due_day', models.IntegerField()),
                ('days_past_due', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='financial_restructuring.customercashflow')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
